@api_HostAddress = http://localhost:5236

GET {{api_HostAddress}}/api/jobs/
Accept: application/json

###

GET {{api_HostAddress}}/api/jobs/Gauteng
Accept: application/json

###

POST {{api_HostAddress}}/api/pipeline/run
Accept: application/json
Content-Type: application/json